# Generated by Django 5.0.4 on 2024-11-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccountStatus',
            fields=[
                ('ClientAccountStatusID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientAccountStatus1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAMLRiskRating',
            fields=[
                ('ClientAMLRiskRatingID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientAMLRiskRating1', models.CharField(max_length=50)),
                ('Min', models.IntegerField()),
                ('Max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('ClientStatusID', models.IntegerField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('ClientTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientType1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=200)),
                ('CountryCode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientTypeSub1', models.CharField(max_length=50)),
                ('ClientTypeSubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clienttype')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.IntegerField(primary_key=True, serialize=False)),
                ('DateOpened', models.DateField()),
                ('ClientName', models.CharField(max_length=200)),
                ('PEP', models.IntegerField()),
                ('USPerson', models.IntegerField()),
                ('ClientAddress1', models.CharField(max_length=200)),
                ('ClientAddress2', models.CharField(max_length=200)),
                ('ClientAddressCity', models.CharField(max_length=200)),
                ('ClientAddressState', models.CharField(blank=True, max_length=50, null=True)),
                ('ClientAddressZipCode', models.CharField(blank=True, max_length=15, null=True)),
                ('ClientPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('ClientFax', models.CharField(blank=True, max_length=15, null=True)),
                ('ClientEmail', models.CharField(blank=True, max_length=200, null=True)),
                ('ClientWebsite', models.CharField(blank=True, max_length=200, null=True)),
                ('ClientApprovalStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('ClientAccountStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientaccountstatus')),
                ('ClientAMLRiskRatingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientamlriskrating')),
                ('ClientStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientstatus')),
                ('ClientSubType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientsubtype')),
                ('ClientType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clienttype')),
                ('CountryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.country')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=200)),
                ('bank_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_city', models.CharField(max_length=150)),
                ('bank_state', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(max_length=30)),
                ('swift_code', models.CharField(blank=True, max_length=30, null=True)),
                ('iban_code', models.CharField(blank=True, max_length=30, null=True)),
                ('aba_code', models.CharField(blank=True, max_length=30, null=True)),
                ('intermediary_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('intermediary_bank_address', models.CharField(max_length=200)),
                ('intermediary_bank_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('intermediary_bank_city', models.CharField(blank=True, max_length=150, null=True)),
                ('intermediary_bank_state', models.CharField(blank=True, max_length=20, null=True)),
                ('intermediary_bank_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('intermediary_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('intermediary_swift_code', models.CharField(blank=True, max_length=30, null=True)),
                ('intermediary_iban_code', models.CharField(blank=True, max_length=30, null=True)),
                ('intermediary_aba_code', models.CharField(blank=True, max_length=30, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='clients.client')),
                ('bank_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks_from_here', to='clients.country')),
                ('intermediary_bank_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediary_banks_from_here', to='clients.country')),
            ],
        ),
    ]
