# Generated by Django 5.0.4 on 2024-11-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ClientAddress2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
