# Generated by Django 5.0.4 on 2024-11-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_clientaddress2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiarybank',
            old_name='intermediary_bank',
            new_name='intermediary_bank_name',
        ),
        migrations.AddField(
            model_name='beneficiarybank',
            name='recipient_address',
            field=models.CharField(default='123 Main st', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiarybank',
            name='recipient_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarybank',
            name='recipient_city',
            field=models.CharField(default='New City', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiarybank',
            name='recipient_country',
            field=models.ForeignKey(default=216, on_delete=django.db.models.deletion.CASCADE, related_name='recipients_from_here', to='clients.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiarybank',
            name='recipient_name',
            field=models.CharField(default='John Doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiarybank',
            name='recipient_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarybank',
            name='recipient_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarybank',
            name='intermediary_bank_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
