# Generated by Django 5.0.4 on 2024-12-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_intermediary_bank_beneficiarybank_intermediary_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
