# Generated by Django 5.1.4 on 2025-02-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_country_options'),
        ('core', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_type', models.CharField(choices=[('I', 'Individual'), ('C', 'Corporate')], max_length=1)),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='ClientAMLRiskRatingID',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ClientAccountStatus',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ClientStatusID',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ClientSubType',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ClientType',
        ),
        migrations.RemoveField(
            model_name='client',
            name='CountryID',
        ),
        migrations.RemoveField(
            model_name='clientsubtype',
            name='ClientTypeSubID',
        ),
        migrations.AlterField(
            model_name='beneficiarybank',
            name='bank_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks_from_here', to='core.country'),
        ),
        migrations.AlterField(
            model_name='beneficiarybank',
            name='recipient_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients_from_here', to='core.country'),
        ),
        migrations.AlterField(
            model_name='beneficiarybank',
            name='intermediary_bank_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediary_banks_from_here', to='core.country'),
        ),
        migrations.AlterField(
            model_name='beneficiarybank',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='clients.clientlist'),
        ),
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_name', models.CharField(max_length=250)),
                ('registration_number', models.CharField(max_length=15)),
                ('date_of_incorporation', models.DateField()),
                ('bir_number', models.CharField(max_length=15)),
                ('vat_registration', models.CharField(max_length=15)),
                ('parent_company', models.CharField(blank=True, max_length=250, null=True)),
                ('registered_address', models.CharField(max_length=200)),
                ('registered_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('registered_city', models.CharField(max_length=150)),
                ('mailing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('primary_phone', models.CharField(max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('telephone_preferred', models.BooleanField(default=False)),
                ('email_preferred', models.BooleanField(default=False)),
                ('website', models.CharField(max_length=250)),
                ('entity_type', models.CharField(choices=[('L', 'Limited Liability'), ('P', 'Partnership'), ('T', 'Trust'), ('S', 'Sole Trader'), ('G', 'Government Enterprise'), ('O', 'Other')], max_length=1)),
                ('business_type', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_frequency', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Annually')], max_length=1)),
                ('politically_exposed', models.BooleanField(default=False)),
                ('political_details', models.CharField(blank=True, max_length=200, null=True)),
                ('client_list_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_corporation', to='clients.clientlist')),
                ('country_of_incorporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_incorporated_here', to='core.country')),
                ('mailing_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corp_clients_mailed_here', to='core.country')),
                ('registered_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_registered_here', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('surname', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('O', 'Other')], max_length=1)),
                ('residential_address', models.CharField(max_length=200)),
                ('residential_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('residential_city', models.CharField(max_length=150)),
                ('mailing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=150, null=True)),
                ('dual_citizen', models.BooleanField(default=False)),
                ('primary_phone', models.CharField(max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('telephone_preferred', models.BooleanField(default=False)),
                ('email_preferred', models.BooleanField(default=False)),
                ('primary_income_source', models.CharField(max_length=200)),
                ('employment_status', models.CharField(choices=[('E', 'Employed'), ('S', 'Self-Employed'), ('O', 'Other')], max_length=1)),
                ('position_held', models.CharField(blank=True, max_length=200, null=True)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('employer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('business_type', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_frequency', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Annually')], max_length=1)),
                ('politically_exposed', models.BooleanField(default=False)),
                ('political_details', models.CharField(blank=True, max_length=200, null=True)),
                ('client_list_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_individual', to='clients.clientlist')),
                ('country_of_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_born_here', to='core.country')),
                ('dual_nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_dual_nationality', to='core.country')),
                ('mailing_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_mailed_here', to='core.country')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_nationality', to='core.country')),
                ('residential_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_residing_here', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.identificationtype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.individualclient')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientAMLRiskRating',
        ),
        migrations.DeleteModel(
            name='ClientAccountStatus',
        ),
        migrations.DeleteModel(
            name='ClientStatus',
        ),
        migrations.DeleteModel(
            name='ClientSubType',
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
