# Generated by Django 5.1.4 on 2025-02-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientlist_remove_client_clientamlriskratingid_and_more'),
        ('transactions', '0008_alter_transaction_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
