# Generated by Django 5.1.4 on 2025-02-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientlocalbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlocalbank',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='local_banks', to='clients.clientlist'),
            preserve_default=False,
        ),
    ]
