# Generated by Django 5.1.4 on 2025-03-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_beneficiarybank_account_type_and_more'),
        ('core', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarybank',
            name='bank_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_banks', to='core.country'),
        ),
        migrations.AlterField(
            model_name='beneficiarybank',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_bank_accounts', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='beneficiarybank',
            name='intermediary_bank_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_intermediary_banks', to='core.country'),
        ),
        migrations.AlterField(
            model_name='beneficiarybank',
            name='recipient_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_recipients', to='core.country'),
        ),
    ]
