# Generated by Django 5.1.4 on 2025-03-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_beneficiarybank_bank_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiarybank',
            name='intermediary_account_number',
        ),
    ]
