# Generated by Django 5.0.4 on 2024-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystock',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
