# Generated by Django 5.0.4 on 2024-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_currencystock_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystock',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=16),
        ),
    ]
