# Generated by Django 5.0.4 on 2024-11-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_alter_currencystock_exchange_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencystock',
            old_name='exchange_rate',
            new_name='currency_rate',
        ),
    ]
