# Generated by Django 5.0.4 on 2024-11-21 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_rename_exchange_rate_currencystock_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencystock',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
