# Generated by Django 5.0.4 on 2024-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_currencystock_effective_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_fee', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
