# Generated by Django 5.0.4 on 2024-12-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_alter_currencystock_currency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystock',
            name='adjustment_source',
            field=models.CharField(choices=[('M', 'Manual'), ('X', 'Exchange'), ('F', 'Fake')], max_length=1),
        ),
    ]
