# Generated by Django 5.1.4 on 2025-02-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_alter_currencystock_adjustment_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFLLocalBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_owner', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_city', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_number', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=16)),
                ('account_type', models.CharField(choices=[('CH', 'Checking'), ('SV', 'Savings'), ('MM', 'Money Marke Account'), ('CD', 'Certificate of Deposit')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'DFL Bank Accounts',
            },
        ),
    ]
