# Generated by Django 5.1.4 on 2025-02-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_dfllocalbank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyStock',
        ),
    ]
