# Generated by Django 5.1.4 on 2025-03-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country'),
        ('setup', '0014_delete_currencystock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFLInternationalBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=200)),
                ('bank_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_city', models.CharField(max_length=150)),
                ('bank_state', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(max_length=30)),
                ('swift_code', models.CharField(blank=True, max_length=30, null=True)),
                ('iban_code', models.CharField(blank=True, max_length=30, null=True)),
                ('aba_code', models.CharField(blank=True, max_length=30, null=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_address', models.CharField(max_length=200)),
                ('recipient_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_city', models.CharField(max_length=150)),
                ('recipient_state', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('intermediary_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('intermediary_bank_address', models.CharField(blank=True, max_length=200, null=True)),
                ('intermediary_bank_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('intermediary_bank_city', models.CharField(blank=True, max_length=150, null=True)),
                ('intermediary_bank_state', models.CharField(blank=True, max_length=20, null=True)),
                ('intermediary_bank_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('intermediary_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('intermediary_swift_code', models.CharField(blank=True, max_length=30, null=True)),
                ('intermediary_iban_code', models.CharField(blank=True, max_length=30, null=True)),
                ('intermediary_aba_code', models.CharField(blank=True, max_length=30, null=True)),
                ('account_type', models.CharField(choices=[('CH', 'Checking'), ('SV', 'Savings'), ('MM', 'Money Marke Account'), ('CD', 'Certificate of Deposit')], max_length=2)),
                ('bank_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_banks', to='core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_bank_accounts', to='core.currency')),
                ('intermediary_bank_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_intermediary_banks', to='core.country')),
                ('recipient_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_recipients', to='core.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
