# Generated by Django 5.1.4 on 2025-03-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_dflinternationalbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dflinternationalbank',
            name='intermediary_account_number',
        ),
    ]
