# Generated by Django 5.0.4 on 2024-11-16 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField()),
                ('value_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('P', 'Purchase'), ('S', 'Sale')], max_length=1)),
                ('origin_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=16)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.beneficiarybank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('deal_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dealstatus')),
                ('origin_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhanged_from', to='core.currency')),
                ('settlement_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanged_to', to='core.currency')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
