# Generated by Django 5.0.4 on 2024-12-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_last_updated_by_alter_transaction_trader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='origin_amount',
            new_name='foreign_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='origin_currency',
            new_name='foreign_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='origin_currency_rate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='foreign_currency_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_currency_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
