# Generated by Django 5.0.4 on 2024-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_origin_amount_transaction_foreign_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
