# Generated by Django 5.1.4 on 2025-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_bank_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash_settlement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fixed_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fixed_deposit_cert',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
