# Generated by Django 5.1.4 on 2025-02-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientlist_remove_client_clientamlriskratingid_and_more'),
        ('transactions', '0007_transaction_cash_settlement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientlist'),
        ),
    ]
