# Generated by Django 5.1.4 on 2025-02-24 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clientlocalbank_client'),
        ('core', '0002_country'),
        ('setup', '0014_delete_currencystock'),
        ('transactions', '0008_alter_transaction_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='check_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dfl_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.dfllocalbank'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('local', 'Local Bank Transfer'), ('foreign', 'Foreign Bank Account')], default='foreign', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='local_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientlocalbank'),
        ),
        migrations.CreateModel(
            name='CurrencyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_source', models.CharField(choices=[('M', 'Manual'), ('X', 'Exchange'), ('F', 'Fake')], max_length=1)),
                ('adjustment_type', models.IntegerField(choices=[(1, 'Increase'), (-1, 'Decrease')])),
                ('currency_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('effective_date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
    ]
